# options for analysis running
run:
  # default concurrency is a available CPU number
  concurrency: 4
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 10m
linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - errcheck
    - staticcheck
    - errorlint
    - typecheck
    - dupl
    - goprintffuncname
    - govet
    - nolintlint
    - rowserrcheck
    - gofmt
    - revive
    - goimports
    - misspell
    - bodyclose
    - unconvert
    - ineffassign
    - staticcheck
    - exportloopref
    - dogsled
    - errcheck
    - funlen
    - gci
    - goconst
    - gocritic
    - gocyclo
    - gosimple
    - gomnd
    - gofmt
    - gosec
    - stylecheck
    - unused
    - unparam
    - unconvert
    - whitespace
linters-settings:
  funlen:
    lines: 84
    statements: 42
  gci:
    sections:
      - standard
      - default
