http://localhost:8000/connect/authorize?client_id=myclient&response_type=code&scope=openid%20profile%20email%20offline_access&code_challenge=pHEZOnt9SDir39wPbXSr0bxiBtkAQFISimcAuVCTkh8&code_challenge_method=S256&redirect_uri=http://localhost:8080/callback&state=1234zyx

###

POST /connect/token HTTP/1.1
Host: localhost:8000
Accept: application/json
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code
&redirect_uri=http://localhost:8080/callback
&code=42b51b278956422c9d7456eda98a3a97046e5efa0a7d4c04831e2bbbb5e2ef74
&code_verifier=7073d688b6dcb02b9a2332e0792be265b9168fda7a6

###

POST /connect/token HTTP/1.1
Host: localhost:8000
Accept: application/json
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token
&client_id=myclient
&client_secret=secret
&refresh_token=4d4379090d5746f3bbb3c58d270f9522489f2c5905dc4ef29199e8629534c1be

###
